name: Savanna

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go_version: '1.22'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

  test:
    runs-on: ubuntu-latest
    needs: setup
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      SMS_SANDBOX_API_KEY: ${{ secrets.SMS_SANDBOX_API_KEY }}
      SMS_SANDBOX_API_USERNAME: ${{ secrets.SMS_SANDBOX_API_USERNAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: go test ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      SMS_SANDBOX_API_KEY: ${{ secrets.SMS_SANDBOX_API_KEY }}
      SMS_SANDBOX_API_USERNAME: ${{ secrets.SMS_SANDBOX_API_USERNAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: go build main.go

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_HOST='${{ secrets.DB_HOST }}'
          DB_PORT='${{ secrets.DB_PORT }}'
          DB_USER='${{ secrets.DB_USER }}'
          DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
          DB_NAME='${{ secrets.DB_NAME }}'
          CLIENT_ID='${{ secrets.CLIENT_ID }}'
          CLIENT_SECRET='${{ secrets.CLIENT_SECRET }}'
          REDIRECT_URI='${{ secrets.REDIRECT_URI }}'
          SMS_SANDBOX_API_KEY='${{ secrets.SMS_SANDBOX_API_KEY }}'
          SMS_SANDBOX_API_USERNAME='${{ secrets.SMS_SANDBOX_API_USERNAME }}'
          EOF

      - name: Deploy
        run: go build main.go
